CREATE TABLE users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email varchar(255) UNIQUE, password varchar(255), wallet_address varchar(66) UNIQUE,
 points integer NOT NULL CHECK(points>=0), version bigint NOT NULL DEFAULT 0,
 created_at timestamp, updated_at timestamp,
 CHECK(email IS NOT NULL OR wallet_address IS NOT NULL),
 CHECK(wallet_address IS NULL OR wallet_address ~ '^0x[0-9a-f]{64}$')
);
CREATE TABLE characters (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 0,
 user_id bigint NOT NULL REFERENCES users(id), name varchar(255) NOT NULL,
 birthday date, relationship_type varchar(255) NOT NULL, gender varchar(255) NOT NULL,
 summary varchar(500), appearance text, personality text, system_prompt text NOT NULL,
 image_prompt text, profile_image_url varchar(2048), call_name varchar(255), soul_id varchar(255),
 created_at timestamp, updated_at timestamp
);
CREATE INDEX characters_user ON characters(user_id,id);
CREATE TABLE character_speech_style (
 character_id bigint NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
 speech_style varchar(255) NOT NULL, style_order integer NOT NULL CHECK(style_order>=0),
 PRIMARY KEY(character_id,style_order)
);
CREATE INDEX speech_style_character ON character_speech_style(character_id);
CREATE TABLE episodes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code varchar(255) NOT NULL UNIQUE,
 title varchar(255) NOT NULL, emoji varchar(255), description varchar(500) NOT NULL,
 scene_prompt_seed text, created_at timestamp, updated_at timestamp
);
CREATE TABLE character_episodes (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 character_id bigint NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
 episode_id bigint NOT NULL REFERENCES episodes(id), status varchar(255) NOT NULL,
 created_at timestamp, updated_at timestamp,
 UNIQUE(character_id,episode_id), UNIQUE(id,character_id)
);
CREATE TABLE chat_messages (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 character_id bigint NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
 character_episode_id bigint, sender varchar(255) NOT NULL CHECK(sender IN ('USER','AI')),
 content text NOT NULL, created_at timestamp, updated_at timestamp,
 FOREIGN KEY(character_episode_id,character_id) REFERENCES character_episodes(id,character_id)
);
CREATE INDEX messages_context ON chat_messages(character_id,character_episode_id,created_at,id);
CREATE TABLE photos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 character_id bigint NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
 type varchar(255) NOT NULL CHECK(type IN ('PROFILE','PHOTOBOOTH')), concept varchar(255),
 prompt_text text, image_url varchar(2048) NOT NULL, selected boolean NOT NULL DEFAULT false,
 created_at timestamp, updated_at timestamp
);
CREATE INDEX photos_character ON photos(character_id,type,id);
